language: node_js
node_js:
  - "node"

services:
  - mysql

branches:
  only:
    - main

cache:
  directories:
    - node_modules

env:
  - NODE_ENV=test

install:
  - npm install -g
  - npm install mocha chai chai-http express jsonwebtoken sequelize mysql2 dotenv

script:
  - npm test
