language: node_js
node_js:
  - 12

before_script:
  - npm install
  - npm install dotenv
  - npm install express
  - npm install jsonwebtoken
  - npm install mysql2
  - npm install sequelize
  - npm install chai
  - npm install chai-http
  - npm install mocha

install:
  - npm run build

branches:
  only:
    - main

notifications:
  email:
    recipients:
      - vixx170627@gmail.com

cache:
  directories:
    - node_modules



env:
  - NODE_ENV: test PORT=3000

script:
  - nohup npm run start &
  - sleep 3
  - npm run start
