language: node_js
node_js:
  - 12

sudo: true

services:
  - mysql

branches:
  only:
    - main

cache:
  directories:
    - node_modules

env:
  - NODE_ENV=test

before_install:
  - npm install -g
  - npm install mocha chai chai-http express jsonwebtoken sequelize dotenv
  - npm install -g mysql2
  - mysql -e 'create database belink_test;'
install:



before_scripts:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('0000') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u travis
  

script:
  - npm test
