language: node_js
node_js:
  - 12

branches:
  only:
    - main

services:
  - mysql

cache:
  directories:
    - node_modules

env:
  - NODE_ENV=test

script:
  - echo '*****Bulid starts*****'
  - echo 'Installing Dependencies'
  - echo 'Running tests'
  - mocha
