language: node_js
node_js:
  - 12

sudo: true

services:
  - mysql

branches:
  only:
    - main

cache:
  directories:
    - node_modules

env:
  - NODE_ENV=test

before_install:
  - npm install -g
  - npm install mocha chai chai-http express jsonwebtoken sequelize dotenv
  - npm install -g mysql2
  - mysql -u root
  - mysql -e 'use mysql;'
  - mysql -e "UPDATE user SET authentication_string=null WHERE User='root';"
  - mysql -e "FLUSH PRIVILEGES;EXIT;"
  - mysql -u root
  - mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '0000';"

  
install:



before_scripts:
  
  

script:
  - npm test
